# Generated by Django 3.2.4 on 2022-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0014_file_str_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicionlogo',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
