# Generated by Django 4.0.4 on 2022-04-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0016_auto_20220410_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicionlogo',
            name='linkqrcod',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
