# Generated by Django 4.0.4 on 2022-04-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0017_posicionlogo_linkqrcod'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicionlogo',
            name='slogan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
