# Generated by Django 4.0.4 on 2022-05-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0020_suscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'Suscripcion', 'verbose_name_plural': 'Suscripciones'},
        ),
    ]
