# Generated by Django 4.0.4 on 2022-05-28 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadapp', '0021_alter_suscripcion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia Suscripcion',
                'verbose_name_plural': 'Historia Suscripciones',
            },
        ),
    ]
