# Generated by Django 4.0.4 on 2022-05-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0022_historia_suscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_suscripcion',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
