# Generated by Django 4.0.4 on 2023-06-20 17:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadapp', '0024_suscripcion_mensual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscripcion_Mensual',
            new_name='Suscripcion_Mensual_Info_Historico',
        ),
    ]
