# Generated by Django 4.0.4 on 2023-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0025_rename_suscripcion_mensual_suscripcion_mensual_info_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
