# Generated by Django 4.0.4 on 2023-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0026_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='B64_Factura_SP',
            field=models.TextField(default=12345),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='Str_Id_Usuario',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
