# Generated by Django 4.0.4 on 2023-06-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0028_alter_file_str_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Str_Id_Usuario',
            new_name='Int_Id_Usuario',
        ),
    ]
