# Generated by Django 4.0.4 on 2023-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0029_rename_str_id_usuario_file_int_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Int_Id_Usuario',
        ),
        migrations.AddField(
            model_name='file',
            name='Str_Usuario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
