# Generated by Django 4.0.4 on 2023-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0032_rename_b64_factura_sp_posicionlogo_facsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicionlogo',
            name='fecha',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
