# Generated by Django 4.0.4 on 2023-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0033_alter_posicionlogo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicionlogo',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
