# Generated by Django 4.0.4 on 2023-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0034_alter_posicionlogo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicionlogo',
            name='fecha',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='posicionlogo',
            name='posicion',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='posicionlogo',
            name='size_logo',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='posicionlogo',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
