# Generated by Django 4.0.4 on 2023-06-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0036_alter_suscripcion_mensual_info_historico_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='estado',
        ),
    ]
